### ISSUE TITLE
Chaos v knihovnách

### ISSUE THREAD

**Issue by kaklik** [MLAB-project/kicad-mlab#1]
Přišel mi dotaz od @VCO34 proč máme některé součástky v různém provedení. Příkladem jsou třeba rezistory v pouzdrech 805 které mají jiné provedení než rezistory v pouzdře 603. 

Jsou tu také rozdíly v provedení potisku. Kdy značka diody je překrytá maskou, takže na PCB efektivně není. 

![55849417_975548646168811_1517920091847524352_n](https://user-images.githubusercontent.com/1194177/54991930-4dd9a300-4fbe-11e9-9a0e-0468f3fb9b4a.jpg)

![55575687_424890038245119_1415933825661272064_n](https://user-images.githubusercontent.com/1194177/54991943-529e5700-4fbe-11e9-9af9-45736efe6c3f.jpg)

Můj názor je, že bychom měli začít v maximální míře používat upstreamové kicad knihovny a v našich knihovnách mít poze pro nás specifické součástky.  Zároveň by asi bylo vhodné nové součástky, které může použít někdo jiný tlačit do upstreamu, abychom měli co nejméně komplikací s údržbou knihoven.

**Comment by ChroustJan** [comment]
@kaklik @VCO34  o této situaci víme. Plošně nepředěláváme všechny knihovny:( Vždy upravuji ty co potřebujeme. Dioda není vhodně řešena, ale výrobně to nevadí. Odpory 0603 a 0805 jsou funkční. Oproti Kicad u 0805 máme lépe řešený popisky pro osazovák. 0603 je jiný protože vychází z nového pouzdra Kicad a je v testování zda by nebylo lepší mít ty zakulacené hrany, které by se pak převzaly do 0805. Také jsme mívali o 0805 větší mezeru mezi piny.  KiCad knihovna se hodně posunula dopředu a je tam toho opravdu mnoho. V aktuálně funguji tak, že používám KiCad knihovny když to jde, ale u nás používám ty naše speciální součástky R0805, hřebínky, LED s otvorem a ty co tam už historicky máme a jsou ověřené. Přijde mi škoda plošně tu knihovnu smazat. Nemělo by tam být nic závadného, jen není vše aktualizované dle nových standardů. Protože dřív se osazovák tisk ve vrstvě potisku.

**Comment by VCO34** [comment]
@kaklik , @ChroustJan  Zdravím, určitě bych knihovnu plošně nemazal, jen ty stadardní věci jako R,C,L, SOT SOP a podobné footprinty používal jejich. Z 90% budou odladěné a vyzkoušené, kulaté rohy jsem již používal a s ručním osazením není problém.  Mě osobně jde také o výsledný celkový dojem z DPS. Postavit vedle sebe R0603 a R1206 a každý bude mít jiný styl vzhledu, se mi nezdá moc profi. Ve svých projektech používám postup následující, co má stadard Kicad to použiju - pokud mám individuálního brouka nebo konektor - mám složku lib, kde tyto součástky vytvořím, přímo jmenovitě - co součástka to lib a pouzdro. Ono jich ve výsledku zase tolik není. Kicad jak píšeš se hooodně posunul.

**Comment by ChroustJan** [comment]
V podstatě je to dobrý postup.  Jen my si ty speciální součástky dáváme do MLAB knihovny, aby byly na jednom místě. Prvotně byla taky myšlenka, aby všechny moduly MLAB vypadaly stejně proto potřeba jednotných knihoven:(, třeba nepříjemné je to jejich pouzdro 0805, protože v osazovací vrstvě není hodnota součástky. Je to hodně šikovné při osazování, když vidíš rovnou i hodnotu součástky, ale tohle lidi při návrh moc nezajímá. Taky to pouzdro R0805 dávám i pro kondenzátory. Když to shrnu, tak pro běžné moduly je nejzásadnější to naše pouzdro pro 0805, pak ta LED s vrtacím otvorem a hřebínky, ale nevím jak se aktuálně liší od KiCad knihovny. Měli jsme zas speciálně vyladěné otvory a plošky. Co s tím @kaklik  provedeme? Napíšeme na wiki návod, aby návrháři používali z našich knihoven jen tyto zmíněné pouzdra s tím, že tam mohou ukládat speciální, které jsou potřebné pro daný modul? Máme totiž také problém s tím, že někdo má vlastní knihovny, které nikdo nedá a pokud se modul předělává, tak někdy nastane problém s překreslováním.

**Comment by kaklik** [comment]
@ChroustJan Trochu mě překvapuje, že už jsi to zavřel, protože mi to nepřijde dořešený. Pokud jsi náhodou už nenapsal někde ten návod. V takovém případě by tu ale na něj měl být odkaz. 

Aby ten návod byl používaný, tak je potřeba, aby obsahoval i vysvětlení proč je důležité používat speciální varianty součástek. Zároveň je myslím důležité se snažit o minimální rozsah vlastních knihoven.  Nepokládám za optimální variantu mít součástky uložené v knihovnách přímo u modulů, neboť v takovém případě bude potíž s udržením aktuálních verzí součástek plošně přes celý projekt v případě, že se speciální IO použije ve více modulech.

**Comment by ChroustJan** [comment]
Návod: https://wiki.mlab.cz/doku.php?id=cs:tools#nastaveni
